name: Update current incident discussion with new information

on:
    
  s     discussions: write
    steps:  
   Add comment to incident discussion
        id: add_comment 
          GITHUB_TOKEN: ${{ 
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
           secrets.GITHUB_TOK utputs.result }}
 d          INCIDENT_MESSAGE: ${{ github.event.client_payload.message }}
